### ISSUE TITLE
Lampadina strada bruciata Via Milano, 144 attraversamento strisce pedonali

### ISSUE THREAD

**Issue by emilianoferrari1** [open-comune/segnala-desio#1]
![immagine](https://cloud.githubusercontent.com/assets/17992225/22878772/4e9c50e6-f1db-11e6-984e-e9255bf05a90.png)

**Comment by olistik** [comment]
@emilianoferrari1 hai fatto anche la segnalazione al Comune?

**Comment by emilianoferrari1** [comment]
Ieri sera ho visto che hanno sostituito la lampadina, direi di chiudere l'argomento.

Ergo: Twitter rimane il miglior strumento di segnalazione per Desio ...
